### ISSUE TITLE
enable insertion and deletion events in evolution along the tree

### ISSUE THREAD

**Issue by dlaehnemann** [sjspielman/pyvolve#10]
Hi again, @sjspielman 

for our simulation pipeline (mentioned in issue #9, and I'll link it once we switch it to public), @VSack and I have implemented `pyvolve` with the substitution mutations it offers, because we like how systematically it is implemented, how well it is documented and how fast it runs.

However, optimally, we were looking for a tool that would also allow the incorporation of insertions and deletions, as these occur in data and to address them in method development, we would need benchmarking data that includes such indels. We saw that you previously started on some indel functionality, but [eventually discarded it](https://github.com/sjspielman/pyvolve/commit/fa3560f19752ebec6139aaf6e863ca627c80f265). Thus we were wondering if there were any further plans for making insertions and deletions available? And if there would be anything we could do to help or discuss the problems with incorporating indels? Or if you would be open to Pull Requests in the midterm, should we at some point have the time/resources to try an implementation ourselves?

Maybe as a reference of a tool that does include insertions and deletions (but eventually runs too slowly for the tree sizes and sequence lengths we want to look at), [the R package phyloSIM](https://github.com/bsipos/phylosim) might be interesting. Especially the `Deletor` and `Insertor` classes seem like a good abstraction, e.g. the [`ContinuousDeletor`](https://github.com/bsipos/phylosim/blob/master/ContinuousDeletor.R).

Best regards,
David

**Comment by sjspielman** [comment]
Hi David, 

This is a bit of complicated issue. The reason I started and then deleted is that I came to believe we do sufficiently understand the biological process of indels, and how insertions/deletions should relate to substitutions. Specifically, it is trivial to simulate the length and location of an indel, but it is NOT trivial to decide how to evolve inserted sequences. Many programs which do implement indels will either i) apply the substitution model from the neighboring site in order evolve insertions, or ii) randomly select substitution parameters for the new site(s). Neither of these solutions is biologically satisfying. Indeed, there should be some salient evolutionary, structural, or functional differences between sites or regions of a protein which can be deleted or can tolerate insertions, and those which can't tolerate such changes (see for example [this paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0164905) where we attempted to identify structural properties related to deletion using one of the only experimental deletion tolerance datasets). 
Because of this *biological* concern, I have opted to maintain pyvolve as a way to evolve sequences under markov models, which an emphasis on model development and testing. These models themselves are not terribly biological, so introducing yet another layer of biological implausibility makes me feel extremely uneasy. 

In the future, I hope to investigate this issue more thoroughly, at which point I would implement indels into pyvolve in a way I feel comfortable with. For now, I would encourage you to fork pyvolve and implement indel functionality to your liking, but I do not currently want full-fledged indel features in the official rep. I am happy to discuss further if you would like. 

Best, 
Stephanie

**Comment by dlaehnemann** [comment]
Hi Stephanie,

thanks already for the quick and detailed response with an interesting reference. I can fully understand your reservations about indels and their location-specific rates being only poorly understood. This sounds more like a bigger research project in itself.

As for some crude basic indel functionality, we would then follow your suggestion, fork pyvolve and probably add some suffix like `_si` ("simplified indels") for the result, to avoid any confusions of future version numbers (but with proper attribution, of course!). I'll also let you know, should we get on this -- for now we will probably just stick with substitutions. Out of curiosity and to estimate how much work such a fork would be: Did your initial indel code actually work?

Thanks a lot once more and for me this issue is thus closed, unless you want to keep it open as a reminder...

Best regards,
David

**Comment by sjspielman** [comment]
Hi David, 

Absolutely no clue about initial code; I haven't looked at it in 3 years...... You're welcome to play around with it but I can neither tell you what it does nor guarantee it does anything useful! 

Ultimately I don't think it would be a huge amount of work to get simplified indels going in pyvolve. [indelSeqGen](http://bioinfolab.unl.edu/~cstrope/iSG/) does a decent job, you might want to see their approach.

Best, 
Stephanie

**Comment by dlaehnemann** [comment]
Thanks for the pointer!
