### ISSUE TITLE
AttributeError: 'str' object has no attribute 'model_flag'

### ISSUE THREAD

**Issue by EldhosePoulose** [sjspielman/pyvolve#16]
[error.pdf](https://github.com/sjspielman/pyvolve/files/4232886/error.pdf)

**Comment by EldhosePoulose** [comment]
import pyvolve


#Tree path
aa_tree= "/Users/pouloeld/Documents/PIPJava/AAData/Eldhose_8taxa_100replica_int0.5_el200_tr8_all/sim-0.newick"

#simple amino-acid model
aa_model= pyvolve.Model("WAG")

#Define Equilibrium frequencies
#f= pyvolve.ReadFrequencies("amino_acid", file= "/Users/pouloeld/Documents/PIPJava/AAData/Eldhose_8taxa_100replica_int0.5_el200_tr8_all/sim-0_MSA.fasta", columns= range(1,6))
#frequencies= f.compute_frequencies(savefile= "my_Equil_Fre.txt")
#Partition 
aa_part= pyvolve.Partition(models= aa_model, size= 100)


#Evolve INDELible

my_evolver= pyvolve.Evolver(partitions=aa_part,tree= aa_tree)
my_evolver()

**Comment by sjspielman** [comment]
Dear @EldhosePoulose, 

You are not using pyvolve correct because you have not read in the tree using pyvolve's `read_tree()` function. Please consult the manual or examples in the repository for appropriate use. 
In addition, generally speaking, you have provided code with personal files on your computer, so in most circumstances it is impossible for me to see if either there is a) a bug in pyvolve, or b) a bug in your code. For me to help you, I need to be able to reproduce your code which requires: An uploaded SCRIPT in a usable format (one cannot execute PDFs as python scripts), and the actual FILES you are using. Furthermore, if you have questions, you must actually ask a question rather than copying over code with no context. 

Please be aware I have also addressed the missing citations in the manual and they are present now. Please also see the associated pyvolve publication for further information on references as needed.

Best, 
Stephanie
