### ISSUE TITLE
Error with ECMunrest

### ISSUE THREAD

**Issue by kfuku52** [sjspielman/pyvolve#18]
Thank you for developing the fantastic simulation tool! I've got an error in trying to run an empirical codon model "ECMunrest" The "ECMrest" worked well. The pyvolve version is 1.0.1. I would be glad if you could check it.

```
import pyvolve

tree = pyvolve.read_tree(tree = "(t4:0.785,(t3:0.380,(t2:0.806,(t5:0.612,t1:0.660)myname1:0.762)myname2:0.921):0.207);")
model = pyvolve.Model(model_type='ECMunrest')
partition = pyvolve.Partition(model=model, size=100)
evolver = pyvolve.Evolver(partition=partition, tree=tree)
evolver(
    ratefile='pyvolve_ratefile.txt', 
    infofile='pyvolve_infofile.txt', 
    seqfile='pyvolve_custom_seqfile.fasta', 
    write_anc=True
)
```

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-f7bf84b723a3> in <module>
      9     infofile='pyvolve_infofile.txt',
     10     seqfile='pyvolve_custom_seqfile.fasta',
---> 11     write_anc=True
     12 )

~/anaconda3/lib/python3.6/site-packages/pyvolve/evolver.py in __call__(self, **kwargs)
    190 
    191         # Simulate recursively
--> 192         self._sim_subtree(self.full_tree)
    193 
    194 

~/anaconda3/lib/python3.6/site-packages/pyvolve/evolver.py in _sim_subtree(self, current_node, parent_node)
    553         # We are at the base and must generate root sequence
    554         if (parent_node is None and current_node.root is True):
--> 555             current_node.seq = self._generate_root_seq() # the .seq attribute is actually a list of Site() objects.
    556 
    557         else:

~/anaconda3/lib/python3.6/site-packages/pyvolve/evolver.py in _generate_root_seq(self)
    532 
    533                         elif self.select_root_type == "random":
--> 534                             new_site.int_seq = self._generate_prob_from_unif( root_model.params['state_freqs'] )
    535                         #########################################################################
    536                         part_root.append( new_site )

~/anaconda3/lib/python3.6/site-packages/pyvolve/evolver.py in _generate_prob_from_unif(self, prob_array)
    457             Arugment *prob_array* is any list and/or numpy array of probabilities which sum to 1.
    458         '''
--> 459         assert ( abs(np.sum(prob_array) - 1.) < ZERO), "Probabilities do not sum to 1. Cannot generate a new sequence."
    460         r = rn.uniform(0,1)
    461         i = 0

AssertionError: Probabilities do not sum to 1. Cannot generate a new sequence.
```

**Comment by sjspielman** [comment]
Hi @kfuku52, 

Thanks for bringing this to my attention - I will have a look soon!

Best, 
Stephanie

**Comment by sjspielman** [comment]
Hi @kfuku52 , 

Sorry for the delay here. Remote teaching and associated prep has come to dominate my life these days. This issue has to do with numerical tolerance for the ECMunrest matrix (which by the way you may be the first person to use, so I hadn't caught this before). In pyvolve, I have included the exact matrix as described in their original paper, but the state frequencies from the model don't sum to 1 at pyvolve's tolerance of 1e-8.

For example, if you use something like this, it will work fine since these frequencies are definitely fine:
`model = pyvolve.Model(model_type = "ECMunrest", params={"state_freqs": np.repeat(1/61, 61)})`

I'm looking into the right way to address this now. Stay tuned.

-Stephanie

**Comment by sjspielman** [comment]
I believe I have fixed the issue in the new aptly-named `issue18` branch. If you are able to install and use this to confirm it works out on your end, let me know! Thanks.

**Comment by kfuku52** [comment]
It worked well after installing the branch as: `pip install https://github.com/sjspielman/pyvolve/archive/issue18.zip`


 Thank you very much for your help in the busy season!

Also, I'm wondering if you are planning to implement the site-wise heterogeneity in the empirical codon models in near future. I've found in the manual that this feature is marked "Feel free to email the author to discuss and/or request this feature". I'm looking for a simulation program for this condition, and it's wonderful if accessible in the framework of pyvolve.

**Comment by sjspielman** [comment]
Hi @kfuku52 , 

Great to hear, thanks for checking on your end! This will be included in the next release.

Regarding ASRV for ECM models, this is not something I am planning to implement. This is because the omega parameter in these models has a really unclear interpretation, and these models are not very commonly used in the first place. Moreover, if it were to be implemented, I would not have the time to do so for the foreseeable future (PRs always welcome though!).

That said, you can still implement heterogeneity using the current functionality of pyvolve by using partitions. There are basically three strategies you can follow:

1. Define several ECM models, each with different rate parameters of your choosing. Set up partitions so that you get a certain number of sites for each rate class. Simulate each partition separately, and then you can concatenate the resulting alignments (and shuffle sites if you want). If you explicitly want different dN, dS, kappa, etc among sites, this is the approach you want.

2. Similar approach to #1, but you can define only one ECM model and perform a couple simulations you can then stitch together, and for each simulation re-scale the *branch lengths* using the `scale_tree` argument in `newick.read_tree()`. Because rate/time are not identifiable, this is effectively the same as scaling rates up and down for different sites. If you want the same dN, dS, etc. among sites but have sites evolve overall slower or faster, this is the approach you want.

3. Pyvolve allows you to use custom rate matrices for simulation. You can build your own matrices to the level of ASRV you want, and then simulate using partitions. 

Best, 
Stephanie

**Comment by kfuku52** [comment]
Those workarounds will work perfectly for my purpose! Most likely No. 2 is the one I'm looking for but I'll try the other two methods too to compare the results. Thank you so much!
