### ISSUE TITLE
how to generate mutation base on absolute mutation rate?

### ISSUE THREAD

**Issue by yech1990** [sjspielman/pyvolve#6]
I want to generate mutation on a given tree base on ultra-low mutation, like 10^-10. Thus, mutation should not be observed in the some node. But, no mater how low I set the rate, mutation always happen on each branch.

**Comment by sjspielman** [comment]
Hello, 

It is likely that your branch lengths are relatively much larger than your mutation rate. The mutation rate defines the instantaneous mutation rate, which can indeed be quite low, but if your branch lengths are fairly large, then substitutions will inevitably occur in spite of a low mutation rate, simply because enough time is passing for slowly-occurring mutations to accumulate. Can you send me your tree used for simulation so I can see if this is indeed the reason for why you observe mutations? You may also want to send your full script.

-Stephanie

**Comment by yech1990** [comment]
Thank you Stephanie.
 The tree is generated by `dendropy`. 

```
t = treesim.birth_death_tree(birth_rate=0.9, death_rate=0.1, ntax=1000)
t.write(path='yeast_tree.tre',
        schema='newick',
        suppress_rooting=True,
)

```
